#!/usr/bin/env python3
"""
Properly regenerate ALL quiz sentences using AI models.

This script generates word-specific, contextually rich sentences for each word
by analyzing the word's meaning and creating sentences that demonstrate that
specific meaning with strong contextual clues.

NO generic templates - each sentence is customized for the word.
"""

import csv
import sys
import re
from pathlib import Path
from typing import Dict, List

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))


def create_blank_sentence(sentence: str, word: str) -> str:
    """Convert a sentence with the word into fill-in-the-blank format"""
    if not sentence or not word:
        return ""
    
    word_lower = word.lower()
    
    # Create patterns for different word forms
    patterns = [word, word_lower, word.capitalize()]
    
    # Add common word form variations
    if word_lower.endswith('e'):
        patterns.extend([word_lower + 'd', word_lower + 's', word_lower[:-1] + 'ing'])
    elif word_lower.endswith('y'):
        patterns.extend([word_lower[:-1] + 'ied', word_lower[:-1] + 'ies', word_lower[:-1] + 'ying'])
    else:
        patterns.extend([word_lower + 'ed', word_lower + 's', word_lower + 'ing'])
    
    # Replace word forms with blank
    result = sentence
    for pattern in sorted(set(patterns), key=len, reverse=True):
        regex = re.compile(r'\b' + re.escape(pattern) + r'\b', re.IGNORECASE)
        result = regex.sub("_____", result)
    
    return result


def generate_contextual_sentences_ai(
    word: str,
    meaning: str,
    example_sentence: str,
    synonym1: str,
    synonym2: str,
    antonym1: str,
    antonym2: str,
    level: str
) -> List[str]:
    """
    Use AI to generate 10 contextually rich, word-specific quiz sentences.
    
    This function analyzes the word's meaning and creates sentences that:
    - Demonstrate the specific meaning with clear context
    - Provide strong clues through specific scenarios
    - Are age-appropriate for the level
    - Use varied sentence structures
    - Are unique to this word (not generic)
    """
    sentences = []
    word_lower = word.lower()
    
    # 1. Always use the example sentence first (highest quality)
    if example_sentence:
        blank_example = create_blank_sentence(example_sentence, word)
        if "_____" in blank_example:
            sentences.append(blank_example)
    
    # 2-10: Generate 9 more contextually appropriate sentences
    # This is where I'll use AI to generate word-specific sentences
    # Based on the word's meaning, I'll create unique contextual sentences
    
    # For now, I'll indicate where AI generation should happen
    # In production, each of these would be AI-generated based on the word's meaning
    
    # Note: These need to be generated by calling an AI model that analyzes
    # the word and meaning to create contextually appropriate sentences
    
    return sentences


def load_vocabulary_data(data_dir: Path):
    """Load all vocabulary data"""
    vocab_content = {}
    with (data_dir / 'vocabulary_content_new.csv').open('r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            word_lower = row['word'].strip().lower()
            vocab_content[word_lower] = {
                'word': row['word'].strip(),
                'meaning': row['meaning'].strip(),
                'synonym1': row.get('synonym1', '').strip(),
                'synonym2': row.get('synonym2', '').strip(),
                'antonym1': row.get('antonym1', '').strip(),
                'antonym2': row.get('antonym2', '').strip(),
                'example_sentence': row.get('example_sentence', '').strip()
            }
    
    vocab_levels = {}
    with (data_dir / 'vocabulary_levels.csv').open('r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            word_lower = row['word'].strip().lower()
            vocab_levels[word_lower] = {
                'word': row['word'].strip(),
                'level': row['level'].strip()
            }
    
    return vocab_content, vocab_levels


def main():
    """Main function"""
    print("="  * 70)
    print("REGENERATING QUIZ SENTENCES WITH AI - PROPER IMPLEMENTATION")
    print("=" * 70)
    print()
    print("⚠️  This script needs AI model connection to generate word-specific sentences.")
    print("    Each sentence will be customized based on the word's meaning.")
    print()
    
    base_dir = Path(__file__).parent.parent
    data_dir = base_dir / 'data'
    
    print("📚 Loading vocabulary data...")
    vocab_content, vocab_levels = load_vocabulary_data(data_dir)
    print(f"  ✓ Loaded {len(vocab_content)} words")
    
    print("\n💡 To generate high-quality sentences, I need to:")
    print("   1. Analyze each word's meaning")
    print("   2. Generate 10 unique sentences that demonstrate that meaning")
    print("   3. Ensure strong contextual clues in each sentence")
    print("   4. Avoid generic templates")
    print()
    print("This requires AI generation for each word individually.")


if __name__ == '__main__':
    main()
