#!/usr/bin/env python3
"""
Vocabulary content generator - generates actual content for all words.

This script generates vocabulary content following British English
and the quality criteria in vocabularySpecification.md.
"""

import csv
from pathlib import Path
from typing import Dict, List

# Vocabulary definitions database
# Format: word -> {meaning, synonyms: [s1, s2], antonyms: [a1, a2], example}
VOCAB_CONTENT = {
    # A words
    "abandon": {"meaning": "to leave behind or give up completely", "synonyms": ["desert", "forsake"], "antonyms": ["keep", "retain"], "example": "The crew had to abandon the sinking ship."},
    "abashed": {"meaning": "feeling embarrassed or ashamed", "synonyms": ["embarrassed", "ashamed"], "antonyms": ["proud", "confident"], "example": "She felt abashed after tripping in front of everyone."},
    "abate": {"meaning": "to become less strong or intense", "synonyms": ["decrease", "lessen"], "antonyms": ["increase", "intensify"], "example": "The storm began to abate by evening."},
    "abbreviate": {"meaning": "to make something shorter", "synonyms": ["shorten", "condense"], "antonyms": ["lengthen", "expand"], "example": "We can abbreviate 'Doctor' to 'Dr'."},
    "abduct": {"meaning": "to take someone away by force", "synonyms": ["kidnap", "seize"], "antonyms": ["release", "free"], "example": "The police searched for the man who tried to abduct the child."},
    "aberrant": {"meaning": "different from what is normal or expected", "synonyms": ["abnormal", "unusual"], "antonyms": ["normal", "typical"], "example": "His aberrant behaviour worried his teachers."},
    "aberration": {"meaning": "something that is not normal or expected", "synonyms": ["anomaly", "deviation"], "antonyms": ["norm", "standard"], "example": "The warm weather in January was an aberration."},
    "abhor": {"meaning": "to hate something very strongly", "synonyms": ["detest", "loathe"], "antonyms": ["love", "adore"], "example": "I abhor cruelty to animals."},
    "abhorrent": {"meaning": "causing strong hatred or disgust", "synonyms": ["hateful", "disgusting"], "antonyms": ["pleasant", "delightful"], "example": "The idea of hurting animals is abhorrent to me."},
    "ablest": {"meaning": "having the most skill or ability", "synonyms": ["most capable", "most skilled"], "antonyms": ["weakest", "least capable"], "example": "She was the ablest student in the class."},
    "abode": {"meaning": "a place where someone lives", "synonyms": ["home", "dwelling"], "antonyms": ["workplace", "school"], "example": "The cottage was her humble abode."},
    "abominable": {"meaning": "extremely unpleasant or bad", "synonyms": ["dreadful", "terrible"], "antonyms": ["wonderful", "delightful"], "example": "The abominable weather ruined our picnic."},
    "abomination": {"meaning": "something that causes hatred or disgust", "synonyms": ["disgrace", "outrage"], "antonyms": ["blessing", "delight"], "example": "Littering is an abomination to nature lovers."},
    "abrasive": {"meaning": "rough or harsh in manner or texture", "synonyms": ["rough", "harsh"], "antonyms": ["gentle", "smooth"], "example": "His abrasive comments upset his classmates."},
    "absence": {"meaning": "the state of being away or not present", "synonyms": ["lack", "nonattendance"], "antonyms": ["presence", "attendance"], "example": "Her absence from school was noticed by the teacher."},
    "absolute": {"meaning": "complete and total", "synonyms": ["complete", "total"], "antonyms": ["partial", "incomplete"], "example": "The room was in absolute silence."},
    "absolution": {"meaning": "formal forgiveness for wrongdoing", "synonyms": ["forgiveness", "pardon"], "antonyms": ["blame", "condemnation"], "example": "He sought absolution for his mistakes."},
    "absorbed": {"meaning": "fully focused on something", "synonyms": ["engrossed", "captivated"], "antonyms": ["distracted", "bored"], "example": "She was absorbed in her book."},
    "abstract": {"meaning": "existing as an idea rather than something physical", "synonyms": ["theoretical", "conceptual"], "antonyms": ["concrete", "tangible"], "example": "Love is an abstract concept."},
    "abstruse": {"meaning": "difficult to understand", "synonyms": ["complex", "obscure"], "antonyms": ["simple", "clear"], "example": "The professor's abstruse explanation confused the students."},
    "absurd": {"meaning": "completely silly or unreasonable", "synonyms": ["ridiculous", "foolish"], "antonyms": ["sensible", "reasonable"], "example": "It was absurd to wear a coat in summer."},
    "abundance": {"meaning": "a very large quantity of something", "synonyms": ["plenty", "wealth"], "antonyms": ["scarcity", "shortage"], "example": "There was an abundance of food at the party."},
    "abundant": {"meaning": "existing in large quantities", "synonyms": ["plentiful", "ample"], "antonyms": ["scarce", "rare"], "example": "The garden was abundant with colourful flowers."},
    "abysmal": {"meaning": "extremely bad or of very poor quality", "synonyms": ["dreadful", "terrible"], "antonyms": ["excellent", "superb"], "example": "His abysmal grades disappointed his parents."},
    "abyss": {"meaning": "a very deep hole or gap", "synonyms": ["chasm", "void"], "antonyms": ["summit", "peak"], "example": "The explorers peered into the dark abyss."},
    "accessible": {"meaning": "easy to reach or use", "synonyms": ["reachable", "available"], "antonyms": ["inaccessible", "unreachable"], "example": "The library is accessible to all students."},
    "acclaim": {"meaning": "enthusiastic praise or approval", "synonyms": ["praise", "applause"], "antonyms": ["criticism", "disapproval"], "example": "The film received widespread acclaim."},
    "accolade": {"meaning": "an award or expression of praise", "synonyms": ["honour", "award"], "antonyms": ["criticism", "disgrace"], "example": "She received an accolade for her bravery."},
    "accusatory": {"meaning": "suggesting someone has done wrong", "synonyms": ["blaming", "critical"], "antonyms": ["supportive", "defending"], "example": "His accusatory tone made her feel guilty."},
    "accuse": {"meaning": "to say someone has done something wrong", "synonyms": ["blame", "charge"], "antonyms": ["defend", "excuse"], "example": "She accused him of taking her pencil."},
    "accustom": {"meaning": "to make familiar with something", "synonyms": ["familiarise", "adapt"], "antonyms": ["estrange", "alienate"], "example": "He had to accustom himself to the cold weather."},
    "acerbic": {"meaning": "sharp and critical in tone", "synonyms": ["harsh", "biting"], "antonyms": ["mild", "gentle"], "example": "Her acerbic wit amused the audience."},
    "acquainted": {"meaning": "familiar with someone or something", "synonyms": ["familiar", "informed"], "antonyms": ["unfamiliar", "ignorant"], "example": "Are you acquainted with our new neighbour?"},
    "acquiescence": {"meaning": "acceptance without protest", "synonyms": ["agreement", "consent"], "antonyms": ["resistance", "refusal"], "example": "His silence was taken as acquiescence."},
    "acquire": {"meaning": "to get or obtain something", "synonyms": ["gain", "obtain"], "antonyms": ["lose", "forfeit"], "example": "She worked hard to acquire new skills."},
    "acrimonious": {"meaning": "angry and bitter in tone", "synonyms": ["bitter", "hostile"], "antonyms": ["friendly", "harmonious"], "example": "The acrimonious debate lasted for hours."},
    "acronym": {"meaning": "a word formed from the first letters of other words", "synonyms": ["abbreviation", "initialism"], "antonyms": ["full form", "expansion"], "example": "NASA is an acronym for National Aeronautics and Space Administration."},
    "across": {"meaning": "from one side to the other", "synonyms": ["over", "through"], "antonyms": ["along", "beside"], "example": "The cat ran across the garden."},
    "acute": {"meaning": "very serious or severe", "synonyms": ["severe", "intense"], "antonyms": ["mild", "slight"], "example": "She felt acute pain in her ankle."},
    "adamant": {"meaning": "refusing to change one's mind", "synonyms": ["determined", "firm"], "antonyms": ["flexible", "yielding"], "example": "He was adamant that he was right."},
    "address": {"meaning": "to speak to or deal with something", "synonyms": ["tackle", "handle"], "antonyms": ["ignore", "avoid"], "example": "The head teacher addressed the assembly."},
    "adequately": {"meaning": "in a satisfactory manner", "synonyms": ["sufficiently", "properly"], "antonyms": ["inadequately", "poorly"], "example": "The task was adequately completed."},
    "adhere": {"meaning": "to stick firmly to something", "synonyms": ["stick", "cling"], "antonyms": ["detach", "separate"], "example": "The sticker will adhere to the surface."},
    "adherent": {"meaning": "a supporter of a belief or cause", "synonyms": ["follower", "supporter"], "antonyms": ["opponent", "critic"], "example": "She is an adherent of healthy eating."},
    "adjacent": {"meaning": "next to or beside something", "synonyms": ["neighbouring", "adjoining"], "antonyms": ["distant", "remote"], "example": "The playground is adjacent to the school."},
    "adjourn": {"meaning": "to stop a meeting temporarily", "synonyms": ["suspend", "postpone"], "antonyms": ["continue", "proceed"], "example": "The judge decided to adjourn the trial until Monday."},
    "admirable": {"meaning": "deserving respect and approval", "synonyms": ["praiseworthy", "commendable"], "antonyms": ["shameful", "disgraceful"], "example": "Her patience with the children was admirable."},
    "admission": {"meaning": "permission to enter or a confession", "synonyms": ["entry", "confession"], "antonyms": ["denial", "rejection"], "example": "Admission to the museum is free on Sundays."},
    "adopt": {"meaning": "to take on or accept something new", "synonyms": ["embrace", "accept"], "antonyms": ["reject", "abandon"], "example": "They decided to adopt a rescue dog."},
    "adore": {"meaning": "to love and respect deeply", "synonyms": ["love", "cherish"], "antonyms": ["hate", "despise"], "example": "The children adore their grandmother."},
    "adorn": {"meaning": "to decorate or make beautiful", "synonyms": ["decorate", "embellish"], "antonyms": ["strip", "bare"], "example": "Flowers adorned the wedding venue."},
    "adulation": {"meaning": "excessive praise or admiration", "synonyms": ["flattery", "praise"], "antonyms": ["criticism", "disapproval"], "example": "The celebrity grew tired of constant adulation."},
    "advance": {"meaning": "to move forward or make progress", "synonyms": ["progress", "proceed"], "antonyms": ["retreat", "withdraw"], "example": "The army began to advance towards the castle."},
    "adventurous": {"meaning": "willing to take risks and try new things", "synonyms": ["daring", "bold"], "antonyms": ["cautious", "timid"], "example": "The adventurous explorer climbed the mountain."},
    "adversary": {"meaning": "an opponent or enemy", "synonyms": ["opponent", "rival"], "antonyms": ["ally", "friend"], "example": "The knight faced his adversary in battle."},
    "adverse": {"meaning": "harmful or unfavourable", "synonyms": ["unfavourable", "negative"], "antonyms": ["favourable", "beneficial"], "example": "The adverse weather delayed the flight."},
    "aeon": {"meaning": "a very long period of time", "synonyms": ["age", "era"], "antonyms": ["moment", "instant"], "example": "It felt like an aeon before the bus arrived."},
    "aesthetic": {"meaning": "relating to beauty or art", "synonyms": ["artistic", "visual"], "antonyms": ["ugly", "unattractive"], "example": "The room had a pleasing aesthetic."},
    "affable": {"meaning": "friendly and easy to talk to", "synonyms": ["friendly", "pleasant"], "antonyms": ["unfriendly", "hostile"], "example": "The affable shopkeeper greeted every customer."},
    "affectionate": {"meaning": "showing love and care", "synonyms": ["loving", "caring"], "antonyms": ["cold", "distant"], "example": "The affectionate puppy licked her face."},
    "affinity": {"meaning": "a natural liking or connection", "synonyms": ["connection", "attraction"], "antonyms": ["aversion", "dislike"], "example": "She has an affinity for languages."},
    "affirmation": {"meaning": "a positive statement or declaration", "synonyms": ["confirmation", "declaration"], "antonyms": ["denial", "rejection"], "example": "His nod was an affirmation of agreement."},
    "affliction": {"meaning": "a cause of pain or suffering", "synonyms": ["suffering", "hardship"], "antonyms": ["comfort", "relief"], "example": "The illness was a great affliction to the family."},
    "affluent": {"meaning": "having a lot of money and possessions", "synonyms": ["wealthy", "rich"], "antonyms": ["poor", "impoverished"], "example": "They lived in an affluent neighbourhood."},
    "aggressor": {"meaning": "a person who attacks first", "synonyms": ["attacker", "assailant"], "antonyms": ["victim", "defender"], "example": "The aggressor was stopped by the police."},
    "aghast": {"meaning": "filled with shock or horror", "synonyms": ["horrified", "shocked"], "antonyms": ["calm", "untroubled"], "example": "She was aghast at the terrible news."},
    "agitated": {"meaning": "feeling nervous or upset", "synonyms": ["anxious", "restless"], "antonyms": ["calm", "relaxed"], "example": "The agitated student paced back and forth."},
    "agnostic": {"meaning": "uncertain about the existence of God", "synonyms": ["doubter", "sceptic"], "antonyms": ["believer", "devout"], "example": "He described himself as agnostic."},
    "agonising": {"meaning": "causing great pain or worry", "synonyms": ["painful", "distressing"], "antonyms": ["painless", "pleasant"], "example": "The wait for results was agonising."},
    "agreeable": {"meaning": "pleasant and willing to agree", "synonyms": ["pleasant", "likeable"], "antonyms": ["disagreeable", "unpleasant"], "example": "She found him to be most agreeable."},
    "aid": {"meaning": "help or support", "synonyms": ["help", "assistance"], "antonyms": ["hindrance", "obstruction"], "example": "The charity provides aid to those in need."},
    "aide": {"meaning": "a person who helps someone important", "synonyms": ["assistant", "helper"], "antonyms": ["boss", "superior"], "example": "The minister's aide arranged the meeting."},
    "ailment": {"meaning": "a minor illness", "synonyms": ["illness", "complaint"], "antonyms": ["health", "wellness"], "example": "She suffered from a common ailment."},
    "alacrity": {"meaning": "eager willingness to do something", "synonyms": ["eagerness", "enthusiasm"], "antonyms": ["reluctance", "hesitation"], "example": "She accepted the invitation with alacrity."},
    "albeit": {"meaning": "although or even though", "synonyms": ["although", "though"], "antonyms": ["because", "since"], "example": "He agreed, albeit reluctantly."},
    "alert": {"meaning": "quick to notice and respond", "synonyms": ["watchful", "attentive"], "antonyms": ["inattentive", "unaware"], "example": "The alert guard noticed the intruder."},
    "alibi": {"meaning": "proof that one was elsewhere when a crime occurred", "synonyms": ["excuse", "defence"], "antonyms": ["accusation", "proof"], "example": "He had a solid alibi for the night of the crime."},
    "alienate": {"meaning": "to make someone feel isolated", "synonyms": ["isolate", "estrange"], "antonyms": ["unite", "connect"], "example": "His rude behaviour alienated his friends."},
    "allay": {"meaning": "to reduce fear or worry", "synonyms": ["calm", "soothe"], "antonyms": ["increase", "worsen"], "example": "She tried to allay his fears about the exam."},
    "alleviate": {"meaning": "to make something less severe", "synonyms": ["ease", "relieve"], "antonyms": ["worsen", "aggravate"], "example": "The medicine helped alleviate the pain."},
    "alluring": {"meaning": "very attractive and tempting", "synonyms": ["attractive", "captivating"], "antonyms": ["repulsive", "unappealing"], "example": "The alluring smell of baking filled the kitchen."},
    "allusion": {"meaning": "an indirect reference to something", "synonyms": ["reference", "hint"], "antonyms": ["statement", "declaration"], "example": "The poem contains an allusion to Greek mythology."},
    "ally": {"meaning": "a person who supports you", "synonyms": ["friend", "partner"], "antonyms": ["enemy", "opponent"], "example": "Britain was an ally of France during the war."},
    "aloof": {"meaning": "unfriendly and distant", "synonyms": ["distant", "detached"], "antonyms": ["friendly", "sociable"], "example": "She seemed aloof and uninterested in conversation."},
    "altercation": {"meaning": "a noisy argument or disagreement", "synonyms": ["quarrel", "dispute"], "antonyms": ["agreement", "harmony"], "example": "The altercation between the neighbours disturbed everyone."},
    "altitude": {"meaning": "the height above sea level", "synonyms": ["height", "elevation"], "antonyms": ["depth", "lowness"], "example": "The plane flew at a high altitude."},
    "altruistic": {"meaning": "caring about others without expecting reward", "synonyms": ["selfless", "generous"], "antonyms": ["selfish", "greedy"], "example": "Her altruistic nature led her to volunteer."},
    "amateur": {"meaning": "someone who does something for enjoyment, not as a job", "synonyms": ["hobbyist", "beginner"], "antonyms": ["professional", "expert"], "example": "He is an amateur photographer."},
    "ambiguous": {"meaning": "having more than one possible meaning", "synonyms": ["unclear", "vague"], "antonyms": ["clear", "definite"], "example": "The instructions were ambiguous and confusing."},
    "ambition": {"meaning": "a strong desire to achieve something", "synonyms": ["drive", "aspiration"], "antonyms": ["apathy", "indifference"], "example": "Her ambition is to become a doctor."},
    "ambivalence": {"meaning": "having mixed feelings about something", "synonyms": ["uncertainty", "indecision"], "antonyms": ["certainty", "decisiveness"], "example": "He felt ambivalence about moving abroad."},
    "ambles": {"meaning": "walks slowly and leisurely", "synonyms": ["strolls", "saunters"], "antonyms": ["rushes", "dashes"], "example": "The dog ambles through the park every morning."},
    "ambling": {"meaning": "walking at a slow, relaxed pace", "synonyms": ["strolling", "wandering"], "antonyms": ["rushing", "hurrying"], "example": "We spent the afternoon ambling through the village."},
    "amend": {"meaning": "to make changes to improve something", "synonyms": ["revise", "correct"], "antonyms": ["worsen", "damage"], "example": "The teacher asked him to amend his essay."},
    "amiable": {"meaning": "friendly and pleasant", "synonyms": ["friendly", "likeable"], "antonyms": ["unfriendly", "hostile"], "example": "The amiable host made everyone feel welcome."},
    "amicable": {"meaning": "friendly and without arguments", "synonyms": ["friendly", "cordial"], "antonyms": ["hostile", "unfriendly"], "example": "They reached an amicable agreement."},
    "amorphous": {"meaning": "without a clear shape or form", "synonyms": ["shapeless", "formless"], "antonyms": ["defined", "structured"], "example": "The amorphous blob of clay needed shaping."},
    "amount": {"meaning": "the total quantity of something", "synonyms": ["quantity", "sum"], "antonyms": ["none", "nothing"], "example": "What is the total amount of money raised?"},
    "amphibian": {"meaning": "an animal that lives both on land and in water", "synonyms": ["frog", "newt"], "antonyms": ["mammal", "reptile"], "example": "A frog is an amphibian."},
    "ample": {"meaning": "more than enough", "synonyms": ["plenty", "sufficient"], "antonyms": ["insufficient", "scarce"], "example": "There was ample food for everyone."},
    "amply": {"meaning": "more than sufficiently", "synonyms": ["generously", "abundantly"], "antonyms": ["scarcely", "barely"], "example": "The evidence amply supports the theory."},
    "amusing": {"meaning": "causing laughter or enjoyment", "synonyms": ["funny", "entertaining"], "antonyms": ["boring", "dull"], "example": "The clown was very amusing."},
    "anagram": {"meaning": "a word formed by rearranging letters of another word", "synonyms": ["wordplay", "puzzle"], "antonyms": ["original", "base word"], "example": "'Listen' is an anagram of 'silent'."},
    "analogy": {"meaning": "a comparison between two things", "synonyms": ["comparison", "similarity"], "antonyms": ["difference", "contrast"], "example": "She drew an analogy between the heart and a pump."},
    "anarchist": {"meaning": "someone who opposes all forms of government", "synonyms": ["rebel", "revolutionary"], "antonyms": ["conformist", "loyalist"], "example": "The anarchist protested against the new laws."},
    "androgynous": {"meaning": "having both male and female characteristics", "synonyms": ["unisex", "gender-neutral"], "antonyms": ["masculine", "feminine"], "example": "The fashion show featured androgynous styles."},
    "anecdote": {"meaning": "a short, interesting story about a real event", "synonyms": ["story", "tale"], "antonyms": ["fact", "report"], "example": "He shared an amusing anecdote about his childhood."},
    "angst": {"meaning": "a feeling of anxiety or worry", "synonyms": ["anxiety", "worry"], "antonyms": ["peace", "calm"], "example": "Teenage angst is common during adolescence."},
    "anguish": {"meaning": "severe mental or physical pain", "synonyms": ["agony", "distress"], "antonyms": ["joy", "comfort"], "example": "She felt deep anguish at the loss of her pet."},
    "animosity": {"meaning": "strong dislike or hatred", "synonyms": ["hostility", "hatred"], "antonyms": ["friendship", "goodwill"], "example": "There was animosity between the rival teams."},
    "annihilated": {"meaning": "completely destroyed", "synonyms": ["destroyed", "eliminated"], "antonyms": ["created", "built"], "example": "The army annihilated the enemy forces."},
    "anomaly": {"meaning": "something that is different from what is normal", "synonyms": ["irregularity", "oddity"], "antonyms": ["norm", "standard"], "example": "The result was an anomaly that puzzled scientists."},
    "antagonistic": {"meaning": "showing opposition or hostility", "synonyms": ["hostile", "unfriendly"], "antonyms": ["friendly", "supportive"], "example": "His antagonistic attitude made cooperation difficult."},
    "antagonize": {"meaning": "to make someone feel hostile", "synonyms": ["provoke", "annoy"], "antonyms": ["please", "calm"], "example": "Stop trying to antagonize your sister."},
    "antidote": {"meaning": "a medicine that counteracts poison", "synonyms": ["remedy", "cure"], "antonyms": ["poison", "toxin"], "example": "The doctor administered an antidote for the snake bite."},
    "antipathy": {"meaning": "a strong feeling of dislike", "synonyms": ["dislike", "aversion"], "antonyms": ["affection", "liking"], "example": "She felt antipathy towards dishonest people."},
    "antiquated": {"meaning": "old-fashioned and outdated", "synonyms": ["outdated", "obsolete"], "antonyms": ["modern", "current"], "example": "The antiquated machinery needed replacing."},
    "antiquity": {"meaning": "the ancient past, especially before the Middle Ages", "synonyms": ["ancient times", "olden days"], "antonyms": ["modernity", "present"], "example": "The vase dates back to antiquity."},
    "antithesis": {"meaning": "the exact opposite of something", "synonyms": ["opposite", "contrast"], "antonyms": ["similarity", "likeness"], "example": "His behaviour was the antithesis of politeness."},
    "antonym": {"meaning": "a word with the opposite meaning", "synonyms": ["opposite", "contrast"], "antonyms": ["synonym", "equivalent"], "example": "'Hot' is an antonym of 'cold'."},
    "anxious": {"meaning": "feeling worried or nervous", "synonyms": ["worried", "nervous"], "antonyms": ["calm", "relaxed"], "example": "She felt anxious before the exam."},
    "apathetic": {"meaning": "showing no interest or enthusiasm", "synonyms": ["indifferent", "uninterested"], "antonyms": ["enthusiastic", "passionate"], "example": "The apathetic student rarely participated in class."},
    "apathy": {"meaning": "lack of interest or concern", "synonyms": ["indifference", "unconcern"], "antonyms": ["interest", "enthusiasm"], "example": "Voter apathy led to low turnout."},
    "aped": {"meaning": "imitated or copied", "synonyms": ["copied", "mimicked"], "antonyms": ["originated", "created"], "example": "The comedian aped the politician's mannerisms."},
    "apex": {"meaning": "the highest point or peak", "synonyms": ["peak", "summit"], "antonyms": ["bottom", "base"], "example": "She reached the apex of her career."},
    "aphorism": {"meaning": "a short, wise saying", "synonyms": ["saying", "maxim"], "antonyms": ["explanation", "elaboration"], "example": "'Actions speak louder than words' is an aphorism."},
    "apoplectic": {"meaning": "extremely angry", "synonyms": ["furious", "enraged"], "antonyms": ["calm", "peaceful"], "example": "He was apoplectic when he heard the news."},
    "apparition": {"meaning": "a ghostly figure", "synonyms": ["ghost", "phantom"], "antonyms": ["reality", "substance"], "example": "The children claimed to have seen an apparition in the old house."},
    "appeal": {"meaning": "to make a serious request", "synonyms": ["request", "plea"], "antonyms": ["demand", "command"], "example": "The charity made an appeal for donations."},
    "appearance": {"meaning": "the way someone or something looks", "synonyms": ["look", "aspect"], "antonyms": ["reality", "substance"], "example": "Her appearance had changed since we last met."},
    "appease": {"meaning": "to calm someone by giving them what they want", "synonyms": ["pacify", "calm"], "antonyms": ["provoke", "anger"], "example": "She tried to appease the crying child with a toy."},
    "apprehension": {"meaning": "worry or fear about what might happen", "synonyms": ["anxiety", "worry"], "antonyms": ["confidence", "assurance"], "example": "He felt apprehension about the job interview."},
    "apprehensive": {"meaning": "worried about what might happen", "synonyms": ["anxious", "nervous"], "antonyms": ["confident", "assured"], "example": "She was apprehensive about starting a new school."},
    "apprise": {"meaning": "to inform someone about something", "synonyms": ["inform", "notify"], "antonyms": ["hide", "conceal"], "example": "Please apprise me of any changes."},
    "approve": {"meaning": "to agree to or accept something", "synonyms": ["accept", "endorse"], "antonyms": ["reject", "disapprove"], "example": "The committee will approve the proposal."},
    "apt": {"meaning": "suitable or appropriate", "synonyms": ["suitable", "fitting"], "antonyms": ["unsuitable", "inappropriate"], "example": "Her comment was very apt."},
    "arbitrary": {"meaning": "based on random choice rather than reason", "synonyms": ["random", "unpredictable"], "antonyms": ["reasoned", "logical"], "example": "The decision seemed arbitrary and unfair."},
    "archaic": {"meaning": "very old or old-fashioned", "synonyms": ["ancient", "outdated"], "antonyms": ["modern", "contemporary"], "example": "The document contained archaic language."},
    "ardour": {"meaning": "strong enthusiasm or passion", "synonyms": ["passion", "enthusiasm"], "antonyms": ["apathy", "indifference"], "example": "He pursued his goals with great ardour."},
    "arduous": {"meaning": "requiring a lot of effort", "synonyms": ["difficult", "strenuous"], "antonyms": ["easy", "simple"], "example": "The climb was arduous but rewarding."},
    "argument": {"meaning": "a reason given to support an idea", "synonyms": ["reasoning", "case"], "antonyms": ["agreement", "consensus"], "example": "She presented a strong argument for her proposal."},
    "arid": {"meaning": "very dry with little rain", "synonyms": ["dry", "parched"], "antonyms": ["wet", "humid"], "example": "The arid desert stretched for miles."},
    "aroma": {"meaning": "a pleasant smell", "synonyms": ["scent", "fragrance"], "antonyms": ["stench", "odour"], "example": "The aroma of freshly baked bread filled the kitchen."},
    "arouse": {"meaning": "to cause a feeling or reaction", "synonyms": ["awaken", "stir"], "antonyms": ["calm", "suppress"], "example": "The speech aroused great interest."},
    "array": {"meaning": "an impressive display or collection", "synonyms": ["collection", "assortment"], "antonyms": ["disorder", "mess"], "example": "An array of colourful flowers decorated the garden."},
    "arrogance": {"meaning": "having too much pride in oneself", "synonyms": ["pride", "conceit"], "antonyms": ["humility", "modesty"], "example": "His arrogance made him unpopular."},
    "artful": {"meaning": "clever and skilled", "synonyms": ["clever", "cunning"], "antonyms": ["artless", "naive"], "example": "The artful detective solved the mystery."},
    "article": {"meaning": "a piece of writing in a newspaper or magazine", "synonyms": ["report", "piece"], "antonyms": ["book", "novel"], "example": "She wrote an article about climate change."},
    "articulate": {"meaning": "able to express ideas clearly", "synonyms": ["eloquent", "fluent"], "antonyms": ["inarticulate", "unclear"], "example": "The articulate speaker impressed the audience."},
    "artisan": {"meaning": "a skilled craftsperson", "synonyms": ["craftsman", "maker"], "antonyms": ["amateur", "novice"], "example": "The artisan made beautiful pottery."},
    "ascendancy": {"meaning": "a position of power or dominance", "synonyms": ["dominance", "supremacy"], "antonyms": ["inferiority", "subordination"], "example": "The team gained ascendancy in the second half."},
    "ascent": {"meaning": "the act of climbing or going up", "synonyms": ["climb", "rise"], "antonyms": ["descent", "fall"], "example": "The ascent of the mountain took three hours."},
    "ascetic": {"meaning": "practising strict self-discipline", "synonyms": ["austere", "self-denying"], "antonyms": ["indulgent", "luxurious"], "example": "The monk lived an ascetic life."},
    "askance": {"meaning": "with suspicion or disapproval", "synonyms": ["suspiciously", "doubtfully"], "antonyms": ["approvingly", "trustingly"], "example": "She looked askance at his unusual request."},
    "aspiration": {"meaning": "a strong hope or ambition", "synonyms": ["ambition", "goal"], "antonyms": ["apathy", "indifference"], "example": "Her aspiration is to become a pilot."},
    "aspire": {"meaning": "to have a strong desire to achieve", "synonyms": ["aim", "hope"], "antonyms": ["despair", "give up"], "example": "She aspires to become a writer."},
    "assemble": {"meaning": "to gather together or put together", "synonyms": ["gather", "collect"], "antonyms": ["scatter", "disperse"], "example": "The students assembled in the hall."},
    "assented": {"meaning": "agreed to a request", "synonyms": ["agreed", "consented"], "antonyms": ["refused", "declined"], "example": "She assented to the proposal after careful thought."},
    "assiduous": {"meaning": "showing great care and effort", "synonyms": ["diligent", "hardworking"], "antonyms": ["lazy", "careless"], "example": "The assiduous student always completed her homework."},
    "assistance": {"meaning": "help or support", "synonyms": ["help", "aid"], "antonyms": ["hindrance", "obstruction"], "example": "She offered her assistance with the project."},
    "assuage": {"meaning": "to make something less intense", "synonyms": ["ease", "relieve"], "antonyms": ["worsen", "intensify"], "example": "She tried to assuage his concerns."},
    "assumption": {"meaning": "something believed without proof", "synonyms": ["belief", "supposition"], "antonyms": ["fact", "proof"], "example": "His assumption proved to be incorrect."},
    "astounding": {"meaning": "surprisingly impressive", "synonyms": ["amazing", "astonishing"], "antonyms": ["ordinary", "unremarkable"], "example": "The magician performed an astounding trick."},
    "astute": {"meaning": "able to understand situations quickly", "synonyms": ["shrewd", "clever"], "antonyms": ["foolish", "naive"], "example": "The astute businessman spotted the opportunity."},
    "asunder": {"meaning": "apart or into pieces", "synonyms": ["apart", "divided"], "antonyms": ["together", "united"], "example": "The storm tore the old fence asunder."},
    "atrocious": {"meaning": "extremely bad or cruel", "synonyms": ["terrible", "awful"], "antonyms": ["excellent", "wonderful"], "example": "The weather was atrocious all week."},
    "attached": {"meaning": "connected or joined to something", "synonyms": ["connected", "joined"], "antonyms": ["detached", "separate"], "example": "The document is attached to the email."},
    "attempt": {"meaning": "to try to do something", "synonyms": ["try", "endeavour"], "antonyms": ["succeed", "achieve"], "example": "She will attempt to break the record."},
    "attentive": {"meaning": "paying close attention", "synonyms": ["alert", "observant"], "antonyms": ["inattentive", "distracted"], "example": "The attentive student listened carefully."},
    "attribute": {"meaning": "a quality or feature", "synonyms": ["quality", "characteristic"], "antonyms": ["flaw", "defect"], "example": "Patience is an important attribute for teachers."},
    "audacious": {"meaning": "showing a willingness to take bold risks", "synonyms": ["bold", "daring"], "antonyms": ["timid", "cautious"], "example": "The audacious plan surprised everyone."},
    "augment": {"meaning": "to make something greater", "synonyms": ["increase", "enhance"], "antonyms": ["decrease", "reduce"], "example": "She took a second job to augment her income."},
    "augmenting": {"meaning": "making something greater or more", "synonyms": ["increasing", "enhancing"], "antonyms": ["decreasing", "reducing"], "example": "The company is augmenting its workforce."},
    "auspicious": {"meaning": "suggesting future success", "synonyms": ["favourable", "promising"], "antonyms": ["unfavourable", "ominous"], "example": "The sunny weather was an auspicious start to the wedding."},
    "austere": {"meaning": "plain and simple, without decoration", "synonyms": ["plain", "simple"], "antonyms": ["luxurious", "ornate"], "example": "The monastery had an austere appearance."},
    "austerity": {"meaning": "strict economy or self-discipline", "synonyms": ["severity", "strictness"], "antonyms": ["luxury", "indulgence"], "example": "The government introduced austerity measures."},
    "authentic": {"meaning": "genuine and real", "synonyms": ["genuine", "real"], "antonyms": ["fake", "false"], "example": "The painting was confirmed to be authentic."},
    "authoritarian": {"meaning": "demanding strict obedience to authority", "synonyms": ["strict", "dictatorial"], "antonyms": ["democratic", "liberal"], "example": "The authoritarian ruler allowed no opposition."},
    "autonomous": {"meaning": "able to act independently", "synonyms": ["independent", "self-governing"], "antonyms": ["dependent", "controlled"], "example": "The region became an autonomous territory."},
    "available": {"meaning": "able to be used or obtained", "synonyms": ["accessible", "obtainable"], "antonyms": ["unavailable", "inaccessible"], "example": "The book is available in the library."},
    "avenge": {"meaning": "to take revenge for a wrongdoing", "synonyms": ["revenge", "retaliate"], "antonyms": ["forgive", "pardon"], "example": "He vowed to avenge his father's death."},
    "average": {"meaning": "typical or ordinary", "synonyms": ["ordinary", "typical"], "antonyms": ["exceptional", "outstanding"], "example": "His marks were average for the class."},
    "aversion": {"meaning": "a strong dislike", "synonyms": ["dislike", "distaste"], "antonyms": ["liking", "fondness"], "example": "She has an aversion to spiders."},
    "avoid": {"meaning": "to keep away from", "synonyms": ["evade", "escape"], "antonyms": ["confront", "face"], "example": "Try to avoid eating too much sugar."},
    "avowed": {"meaning": "openly declared", "synonyms": ["declared", "acknowledged"], "antonyms": ["secret", "hidden"], "example": "She is an avowed supporter of the cause."},
    "awkward": {"meaning": "causing difficulty or embarrassment", "synonyms": ["clumsy", "uncomfortable"], "antonyms": ["graceful", "comfortable"], "example": "There was an awkward silence in the room."},
    "awry": {"meaning": "wrong or not as planned", "synonyms": ["wrong", "amiss"], "antonyms": ["right", "correct"], "example": "Something had gone awry with the plan."},
    "axiom": {"meaning": "a statement accepted as true", "synonyms": ["principle", "truth"], "antonyms": ["falsehood", "lie"], "example": "It is an axiom that practice makes perfect."},
    # B words
    "baleful": {"meaning": "threatening harm or evil", "synonyms": ["menacing", "sinister"], "antonyms": ["kind", "benevolent"], "example": "The villain gave a baleful stare."},
    "balk": {"meaning": "to hesitate or refuse to continue", "synonyms": ["hesitate", "refuse"], "antonyms": ["proceed", "continue"], "example": "The horse balked at the high fence."},
    "banal": {"meaning": "boring and lacking originality", "synonyms": ["dull", "unoriginal"], "antonyms": ["original", "fresh"], "example": "The film had a banal plot."},
    "bane": {"meaning": "a cause of trouble or misery", "synonyms": ["curse", "plague"], "antonyms": ["blessing", "boon"], "example": "Homework is the bane of his existence."},
    "banish": {"meaning": "to send someone away as punishment", "synonyms": ["exile", "expel"], "antonyms": ["welcome", "admit"], "example": "The king banished the traitor from the kingdom."},
    "barbarian": {"meaning": "a person from a primitive culture", "synonyms": ["savage", "brute"], "antonyms": ["civilised", "refined"], "example": "The Roman soldiers fought against the barbarians."},
    "barbaric": {"meaning": "extremely cruel and brutal", "synonyms": ["brutal", "savage"], "antonyms": ["civilised", "humane"], "example": "The barbaric treatment of prisoners was condemned."},
    "bargain": {"meaning": "an agreement between two parties", "synonyms": ["deal", "agreement"], "antonyms": ["disagreement", "conflict"], "example": "They made a bargain to share the treasure."},
    "barren": {"meaning": "unable to produce crops or offspring", "synonyms": ["infertile", "desolate"], "antonyms": ["fertile", "productive"], "example": "The barren desert stretched for miles."},
    "barricade": {"meaning": "a barrier to block passage", "synonyms": ["barrier", "blockade"], "antonyms": ["opening", "passage"], "example": "The protesters built a barricade across the road."},
    "bashful": {"meaning": "shy and easily embarrassed", "synonyms": ["shy", "timid"], "antonyms": ["bold", "confident"], "example": "The bashful child hid behind her mother."},
    "beam": {"meaning": "a ray of light or to smile brightly", "synonyms": ["ray", "glow"], "antonyms": ["darkness", "shadow"], "example": "A beam of sunlight entered the room."},
    "beautiful": {"meaning": "pleasing to look at", "synonyms": ["lovely", "attractive"], "antonyms": ["ugly", "unattractive"], "example": "The sunset was beautiful."},
    "because": {"meaning": "for the reason that", "synonyms": ["since", "as"], "antonyms": ["despite", "although"], "example": "She stayed home because she was ill."},
    "beck": {"meaning": "a small stream", "synonyms": ["stream", "brook"], "antonyms": ["ocean", "sea"], "example": "The children played by the beck."},
    "becoming": {"meaning": "suitable or flattering", "synonyms": ["flattering", "appropriate"], "antonyms": ["unflattering", "unsuitable"], "example": "That colour is very becoming on you."},
    "belies": {"meaning": "gives a false impression of", "synonyms": ["contradicts", "disguises"], "antonyms": ["reveals", "confirms"], "example": "Her calm expression belies her true feelings."},
    "believe": {"meaning": "to accept as true", "synonyms": ["trust", "accept"], "antonyms": ["doubt", "disbelieve"], "example": "I believe you are telling the truth."},
    "belittle": {"meaning": "to make someone feel unimportant", "synonyms": ["dismiss", "disparage"], "antonyms": ["praise", "encourage"], "example": "Don't belittle your achievements."},
    "bellicose": {"meaning": "eager to fight or argue", "synonyms": ["aggressive", "hostile"], "antonyms": ["peaceful", "friendly"], "example": "His bellicose attitude caused many arguments."},
    "belligerent": {"meaning": "hostile and aggressive", "synonyms": ["hostile", "aggressive"], "antonyms": ["peaceful", "friendly"], "example": "The belligerent student was sent to the head teacher."},
    "bemoan": {"meaning": "to complain about something", "synonyms": ["lament", "complain"], "antonyms": ["celebrate", "praise"], "example": "She bemoaned the lack of good weather."},
    "bemused": {"meaning": "puzzled or confused", "synonyms": ["confused", "puzzled"], "antonyms": ["clear", "understanding"], "example": "He had a bemused expression on his face."},
    "benefit": {"meaning": "an advantage or profit", "synonyms": ["advantage", "gain"], "antonyms": ["disadvantage", "harm"], "example": "Regular exercise has many benefits."},
    "benevolent": {"meaning": "kind and generous", "synonyms": ["kind", "generous"], "antonyms": ["cruel", "mean"], "example": "The benevolent king helped the poor."},
    "benign": {"meaning": "gentle and not harmful", "synonyms": ["harmless", "gentle"], "antonyms": ["harmful", "malignant"], "example": "The doctor said the tumour was benign."},
    "bequeath": {"meaning": "to leave something to someone in a will", "synonyms": ["leave", "pass on"], "antonyms": ["inherit", "receive"], "example": "She bequeathed her jewellery to her daughter."},
    "berate": {"meaning": "to scold someone angrily", "synonyms": ["scold", "criticise"], "antonyms": ["praise", "compliment"], "example": "The coach berated the team for their poor performance."},
    "bereft": {"meaning": "deprived of or lacking something", "synonyms": ["deprived", "lacking"], "antonyms": ["possessing", "having"], "example": "She felt bereft after losing her best friend."},
    "besieged": {"meaning": "surrounded by enemy forces", "synonyms": ["surrounded", "trapped"], "antonyms": ["freed", "liberated"], "example": "The castle was besieged for three months."},
    "betray": {"meaning": "to be disloyal to someone", "synonyms": ["deceive", "double-cross"], "antonyms": ["support", "protect"], "example": "He would never betray his friends."},
    "between": {"meaning": "in the space separating two things", "synonyms": ["among", "amid"], "antonyms": ["outside", "beyond"], "example": "The ball landed between the two trees."},
    "beverage": {"meaning": "a drink other than water", "synonyms": ["drink", "refreshment"], "antonyms": ["food", "solid"], "example": "Would you like a hot beverage?"},
    "bewilder": {"meaning": "to confuse or puzzle someone", "synonyms": ["confuse", "puzzle"], "antonyms": ["clarify", "explain"], "example": "The maze bewildered the visitors."},
    "bewildered": {"meaning": "completely confused", "synonyms": ["confused", "perplexed"], "antonyms": ["clear", "certain"], "example": "She looked bewildered by the question."},
    "biased": {"meaning": "unfairly favouring one side", "synonyms": ["prejudiced", "partial"], "antonyms": ["fair", "impartial"], "example": "The referee's decision seemed biased."},
    "bickering": {"meaning": "arguing about unimportant things", "synonyms": ["quarrelling", "squabbling"], "antonyms": ["agreeing", "harmonising"], "example": "The siblings were always bickering."},
    "bicycle": {"meaning": "a two-wheeled vehicle", "synonyms": ["bike", "cycle"], "antonyms": ["car", "bus"], "example": "She rides her bicycle to school."},
    "bipartisan": {"meaning": "involving two political parties", "synonyms": ["cooperative", "joint"], "antonyms": ["partisan", "one-sided"], "example": "They reached a bipartisan agreement."},
    "bittersweet": {"meaning": "both pleasant and painful", "synonyms": ["mixed", "poignant"], "antonyms": ["purely happy", "purely sad"], "example": "Leaving school was a bittersweet moment."},
    "bland": {"meaning": "lacking flavour or interest", "synonyms": ["tasteless", "dull"], "antonyms": ["flavourful", "exciting"], "example": "The food was rather bland."},
    "blasphemy": {"meaning": "speaking disrespectfully about religion", "synonyms": ["sacrilege", "profanity"], "antonyms": ["reverence", "respect"], "example": "In some countries, blasphemy is a crime."},
    "blatant": {"meaning": "very obvious and without shame", "synonyms": ["obvious", "flagrant"], "antonyms": ["subtle", "hidden"], "example": "It was a blatant lie."},
    "bleak": {"meaning": "cold, empty and without hope", "synonyms": ["gloomy", "dreary"], "antonyms": ["bright", "hopeful"], "example": "The winter landscape looked bleak."},
    "bleats": {"meaning": "makes a sound like a sheep", "synonyms": ["cries", "calls"], "antonyms": ["roars", "bellows"], "example": "The lamb bleats for its mother."},
    "blissful": {"meaning": "extremely happy", "synonyms": ["joyful", "happy"], "antonyms": ["miserable", "unhappy"], "example": "They spent a blissful day at the beach."},
    "blossom": {"meaning": "a flower or to develop well", "synonyms": ["bloom", "flower"], "antonyms": ["wilt", "wither"], "example": "The cherry trees began to blossom."},
    "bludgeon": {"meaning": "to hit with a heavy object", "synonyms": ["strike", "beat"], "antonyms": ["caress", "stroke"], "example": "The weapon was used to bludgeon the victim."},
    "boastful": {"meaning": "showing too much pride", "synonyms": ["bragging", "proud"], "antonyms": ["modest", "humble"], "example": "His boastful manner annoyed everyone."},
    "boisterous": {"meaning": "noisy, energetic and cheerful", "synonyms": ["rowdy", "lively"], "antonyms": ["quiet", "calm"], "example": "The boisterous children ran through the house."},
    "bold": {"meaning": "brave and confident", "synonyms": ["brave", "courageous"], "antonyms": ["timid", "cowardly"], "example": "It was a bold decision to climb the mountain."},
    "bolster": {"meaning": "to support or strengthen", "synonyms": ["support", "reinforce"], "antonyms": ["weaken", "undermine"], "example": "The good news helped bolster her confidence."},
    "boon": {"meaning": "something helpful or beneficial", "synonyms": ["blessing", "benefit"], "antonyms": ["curse", "bane"], "example": "The rain was a boon for the farmers."},
    "box": {"meaning": "a container with flat sides", "synonyms": ["container", "case"], "antonyms": ["sphere", "ball"], "example": "Put the toys in the box."},
    "braggart": {"meaning": "a person who boasts", "synonyms": ["boaster", "show-off"], "antonyms": ["modest person", "humble person"], "example": "Nobody likes a braggart."},
    "brandish": {"meaning": "to wave something as a threat", "synonyms": ["wave", "flourish"], "antonyms": ["conceal", "hide"], "example": "The knight brandished his sword."},
    "brawn": {"meaning": "physical strength", "synonyms": ["muscle", "strength"], "antonyms": ["weakness", "frailty"], "example": "The job requires more brawn than brain."},
    "bray": {"meaning": "the loud cry of a donkey", "synonyms": ["cry", "call"], "antonyms": ["whisper", "murmur"], "example": "The donkey let out a loud bray."},
    "brazen": {"meaning": "bold and without shame", "synonyms": ["bold", "shameless"], "antonyms": ["shy", "modest"], "example": "It was a brazen attempt to cheat."},
    "breach": {"meaning": "to break through or violate", "synonyms": ["break", "violate"], "antonyms": ["obey", "observe"], "example": "They breached the castle walls."},
    "breadth": {"meaning": "the width or extent of something", "synonyms": ["width", "extent"], "antonyms": ["narrowness", "length"], "example": "The breadth of his knowledge was impressive."},
    "brevity": {"meaning": "using few words or lasting a short time", "synonyms": ["shortness", "conciseness"], "antonyms": ["length", "wordiness"], "example": "Brevity is the soul of wit."},
    "brief": {"meaning": "lasting a short time", "synonyms": ["short", "concise"], "antonyms": ["long", "extended"], "example": "The meeting was brief."},
    "britain": {"meaning": "the island containing England, Scotland and Wales", "synonyms": ["UK", "Great Britain"], "antonyms": ["foreign country", "abroad"], "example": "Britain has a rich history."},
    "broad": {"meaning": "wide in extent", "synonyms": ["wide", "extensive"], "antonyms": ["narrow", "limited"], "example": "The broad river flowed through the valley."},
    "brooding": {"meaning": "thinking deeply about something worrying", "synonyms": ["pondering", "thinking"], "antonyms": ["carefree", "cheerful"], "example": "He sat in brooding silence."},
    "bruise": {"meaning": "an injury causing skin discolouration", "synonyms": ["contusion", "mark"], "antonyms": ["heal", "cure"], "example": "She got a bruise from falling off her bike."},
    "brusque": {"meaning": "abrupt and curt in manner", "synonyms": ["abrupt", "curt"], "antonyms": ["polite", "courteous"], "example": "His brusque reply was quite rude."},
    "buckle": {"meaning": "a metal clasp for fastening", "synonyms": ["clasp", "fastener"], "antonyms": ["unfasten", "release"], "example": "Buckle your seatbelt before we start."},
    "bumbling": {"meaning": "acting in a confused, clumsy way", "synonyms": ["clumsy", "incompetent"], "antonyms": ["competent", "skilled"], "example": "The bumbling detective couldn't solve the case."},
    "buoyant": {"meaning": "able to float or cheerful", "synonyms": ["floating", "cheerful"], "antonyms": ["sinking", "gloomy"], "example": "She was in a buoyant mood."},
    "burden": {"meaning": "a heavy load or responsibility", "synonyms": ["load", "responsibility"], "antonyms": ["relief", "freedom"], "example": "Caring for elderly parents can be a burden."},
    "burgeon": {"meaning": "to grow or develop rapidly", "synonyms": ["flourish", "thrive"], "antonyms": ["shrink", "decline"], "example": "The business began to burgeon."},
    "business": {"meaning": "a commercial activity or company", "synonyms": ["company", "trade"], "antonyms": ["leisure", "hobby"], "example": "She started her own business."},
    "busk": {"meaning": "to perform music in public for money", "synonyms": ["perform", "play"], "antonyms": ["listen", "watch"], "example": "Musicians often busk in the town centre."},
    "bustling": {"meaning": "full of busy activity", "synonyms": ["busy", "lively"], "antonyms": ["quiet", "deserted"], "example": "The bustling market was full of shoppers."},
    "buttress": {"meaning": "a structure that supports a wall", "synonyms": ["support", "prop"], "antonyms": ["weaken", "undermine"], "example": "The buttress helped support the old church."},
    # C words
    "cache": {"meaning": "a hidden store of things", "synonyms": ["store", "stash"], "antonyms": ["display", "exposure"], "example": "They found a cache of old coins."},
    "cacophony": {"meaning": "a harsh mixture of sounds", "synonyms": ["din", "noise"], "antonyms": ["harmony", "melody"], "example": "The cacophony of car horns filled the street."},
    "cajole": {"meaning": "to persuade by flattery", "synonyms": ["coax", "persuade"], "antonyms": ["force", "demand"], "example": "She tried to cajole him into helping."},
    "calamity": {"meaning": "a sudden disaster", "synonyms": ["disaster", "catastrophe"], "antonyms": ["blessing", "fortune"], "example": "The flood was a calamity for the village."},
    "callous": {"meaning": "showing no concern for others", "synonyms": ["heartless", "cruel"], "antonyms": ["compassionate", "caring"], "example": "His callous remarks hurt her feelings."},
    "callow": {"meaning": "young and inexperienced", "synonyms": ["immature", "naive"], "antonyms": ["mature", "experienced"], "example": "The callow youth had much to learn."},
    "camaraderie": {"meaning": "friendship between people", "synonyms": ["fellowship", "friendship"], "antonyms": ["hostility", "enmity"], "example": "There was great camaraderie among the team."},
    "candid": {"meaning": "honest and direct", "synonyms": ["frank", "honest"], "antonyms": ["dishonest", "evasive"], "example": "She gave a candid interview."},
    "candidate": {"meaning": "a person seeking election or a position", "synonyms": ["applicant", "contender"], "antonyms": ["voter", "selector"], "example": "He is a candidate for class president."},
    "candour": {"meaning": "honesty and openness", "synonyms": ["honesty", "frankness"], "antonyms": ["dishonesty", "deceit"], "example": "I appreciate your candour."},
    "cantankerous": {"meaning": "bad-tempered and argumentative", "synonyms": ["grumpy", "irritable"], "antonyms": ["pleasant", "agreeable"], "example": "The cantankerous old man complained about everything."},
    "capacious": {"meaning": "having lots of space", "synonyms": ["spacious", "roomy"], "antonyms": ["cramped", "small"], "example": "The capacious bag held all her belongings."},
    "capricious": {"meaning": "changing mood or behaviour suddenly", "synonyms": ["unpredictable", "fickle"], "antonyms": ["steady", "constant"], "example": "The capricious weather changed hourly."},
    "captivating": {"meaning": "attracting and holding attention", "synonyms": ["fascinating", "enchanting"], "antonyms": ["boring", "dull"], "example": "The captivating story kept everyone reading."},
    "careering": {"meaning": "moving swiftly in an uncontrolled way", "synonyms": ["rushing", "hurtling"], "antonyms": ["crawling", "stopping"], "example": "The car went careering down the hill."},
    "caricature": {"meaning": "an exaggerated portrayal", "synonyms": ["parody", "cartoon"], "antonyms": ["portrait", "likeness"], "example": "The cartoon was a caricature of the politician."},
    "cascade": {"meaning": "a waterfall or to pour down", "synonyms": ["waterfall", "torrent"], "antonyms": ["trickle", "drip"], "example": "Water cascaded down the rocks."},
    "catastrophe": {"meaning": "a sudden great disaster", "synonyms": ["disaster", "calamity"], "antonyms": ["triumph", "success"], "example": "The earthquake was a catastrophe."},
    "category": {"meaning": "a group of similar things", "synonyms": ["class", "group"], "antonyms": ["individual", "single"], "example": "Books are sorted into categories."},
    "cathartic": {"meaning": "providing relief from emotions", "synonyms": ["cleansing", "releasing"], "antonyms": ["suppressing", "bottling"], "example": "Crying can be cathartic."},
    "caulking": {"meaning": "material used to seal gaps", "synonyms": ["sealant", "filler"], "antonyms": ["opener", "gap"], "example": "The plumber applied caulking to the pipes."},
    "caution": {"meaning": "care taken to avoid danger", "synonyms": ["care", "prudence"], "antonyms": ["recklessness", "carelessness"], "example": "Proceed with caution."},
    "cavorting": {"meaning": "jumping around playfully", "synonyms": ["frolicking", "prancing"], "antonyms": ["sitting", "resting"], "example": "The lambs were cavorting in the field."},
    "cease": {"meaning": "to stop or end", "synonyms": ["stop", "end"], "antonyms": ["continue", "begin"], "example": "The rain ceased by evening."},
    "celestial": {"meaning": "relating to the sky or heaven", "synonyms": ["heavenly", "divine"], "antonyms": ["earthly", "terrestrial"], "example": "The celestial bodies shone brightly."},
    "cemetery": {"meaning": "a place where dead people are buried", "synonyms": ["graveyard", "burial ground"], "antonyms": ["birthplace", "nursery"], "example": "They visited the old cemetery."},
    "censure": {"meaning": "to express strong disapproval", "synonyms": ["criticise", "condemn"], "antonyms": ["praise", "approve"], "example": "The politician faced censure for his actions."},
    "certitude": {"meaning": "complete certainty", "synonyms": ["certainty", "confidence"], "antonyms": ["doubt", "uncertainty"], "example": "She spoke with certitude."},
    "challenging": {"meaning": "testing one's abilities", "synonyms": ["difficult", "demanding"], "antonyms": ["easy", "simple"], "example": "The exam was very challenging."},
    "chameleon": {"meaning": "a lizard that changes colour", "synonyms": ["lizard", "reptile"], "antonyms": ["constant", "unchanging"], "example": "The chameleon changed to match the leaves."},
    "chaos": {"meaning": "complete disorder and confusion", "synonyms": ["disorder", "confusion"], "antonyms": ["order", "calm"], "example": "The room was in chaos after the party."},
    "charismatic": {"meaning": "having a charm that attracts others", "synonyms": ["charming", "magnetic"], "antonyms": ["dull", "unappealing"], "example": "The charismatic leader inspired many."},
    "charlatan": {"meaning": "a person falsely claiming knowledge", "synonyms": ["fraud", "imposter"], "antonyms": ["expert", "genuine"], "example": "The doctor turned out to be a charlatan."},
    "charming": {"meaning": "very pleasant and attractive", "synonyms": ["delightful", "appealing"], "antonyms": ["unpleasant", "repulsive"], "example": "The village was absolutely charming."},
    "charred": {"meaning": "burnt and blackened", "synonyms": ["burnt", "scorched"], "antonyms": ["fresh", "unburnt"], "example": "The charred remains of the building were cleared."},
    "chastised": {"meaning": "scolded or punished", "synonyms": ["scolded", "reprimanded"], "antonyms": ["praised", "rewarded"], "example": "She was chastised for being late."},
    "chauvinist": {"meaning": "a person with excessive patriotism or prejudice", "synonyms": ["bigot", "sexist"], "antonyms": ["egalitarian", "fair"], "example": "He was criticised for being a chauvinist."},
    "cherished": {"meaning": "held dear and protected", "synonyms": ["treasured", "valued"], "antonyms": ["neglected", "ignored"], "example": "The cherished memories lasted a lifetime."},
    "chicanery": {"meaning": "trickery or deception", "synonyms": ["trickery", "deception"], "antonyms": ["honesty", "fairness"], "example": "The politician was accused of chicanery."},
    "chivalrous": {"meaning": "courteous and gallant", "synonyms": ["gallant", "courteous"], "antonyms": ["rude", "discourteous"], "example": "The chivalrous knight helped the lady."},
    "choreographer": {"meaning": "a person who creates dance routines", "synonyms": ["dance director", "dance creator"], "antonyms": ["dancer", "performer"], "example": "The choreographer designed the ballet."},
    "chortle": {"meaning": "to laugh in a breathy way", "synonyms": ["chuckle", "giggle"], "antonyms": ["cry", "weep"], "example": "He chortled at the funny joke."},
    "chronicle": {"meaning": "a record of events in order", "synonyms": ["record", "account"], "antonyms": ["fiction", "invention"], "example": "The book chronicles the history of the town."},
    "chronology": {"meaning": "the arrangement of events in time order", "synonyms": ["timeline", "sequence"], "antonyms": ["disorder", "chaos"], "example": "The chronology of events was confusing."},
    "clamber": {"meaning": "to climb awkwardly", "synonyms": ["scramble", "climb"], "antonyms": ["descend", "fall"], "example": "The children clambered over the rocks."},
    "clamour": {"meaning": "a loud noise or protest", "synonyms": ["noise", "outcry"], "antonyms": ["silence", "quiet"], "example": "There was a clamour for change."},
    "clemency": {"meaning": "mercy or leniency", "synonyms": ["mercy", "leniency"], "antonyms": ["harshness", "severity"], "example": "The prisoner begged for clemency."},
    "clement": {"meaning": "mild and pleasant weather", "synonyms": ["mild", "pleasant"], "antonyms": ["harsh", "severe"], "example": "The clement weather was perfect for a picnic."},
    "cliché": {"meaning": "an overused phrase or idea", "synonyms": ["stereotype", "commonplace"], "antonyms": ["original", "novel"], "example": "'Time flies' is a cliché."},
    "coarse": {"meaning": "rough in texture or rude", "synonyms": ["rough", "crude"], "antonyms": ["smooth", "refined"], "example": "The coarse fabric scratched her skin."},
    "coax": {"meaning": "to gently persuade someone", "synonyms": ["persuade", "cajole"], "antonyms": ["force", "coerce"], "example": "She coaxed the kitten out of hiding."},
    "coerce": {"meaning": "to force someone to act", "synonyms": ["force", "compel"], "antonyms": ["persuade", "allow"], "example": "He was coerced into signing the contract."},
    "coercion": {"meaning": "the use of force to persuade", "synonyms": ["force", "pressure"], "antonyms": ["persuasion", "choice"], "example": "The confession was obtained through coercion."},
    "coherent": {"meaning": "logical and easy to understand", "synonyms": ["logical", "clear"], "antonyms": ["incoherent", "confused"], "example": "She gave a coherent explanation."},
    "coincidence": {"meaning": "things happening by chance together", "synonyms": ["chance", "accident"], "antonyms": ["plan", "design"], "example": "What a coincidence meeting you here!"},
    "collaborate": {"meaning": "to work together on something", "synonyms": ["cooperate", "work together"], "antonyms": ["compete", "oppose"], "example": "The two artists collaborated on the project."},
    "college": {"meaning": "an educational institution", "synonyms": ["university", "academy"], "antonyms": ["workplace", "office"], "example": "She went to college to study medicine."},
    "colloquial": {"meaning": "used in ordinary conversation", "synonyms": ["informal", "casual"], "antonyms": ["formal", "literary"], "example": "'Kids' is a colloquial word for children."},
    "colour": {"meaning": "the property of light that gives things their appearance", "synonyms": ["hue", "shade"], "antonyms": ["colourless", "monochrome"], "example": "What is your favourite colour?"},
    "combat": {"meaning": "fighting or to fight against", "synonyms": ["fight", "battle"], "antonyms": ["peace", "surrender"], "example": "Soldiers engaged in combat."},
    "combination": {"meaning": "a joining of different things", "synonyms": ["mixture", "blend"], "antonyms": ["separation", "division"], "example": "The combination of colours was beautiful."},
    "comforting": {"meaning": "making someone feel better", "synonyms": ["soothing", "reassuring"], "antonyms": ["distressing", "upsetting"], "example": "Her words were very comforting."},
    "comical": {"meaning": "funny and amusing", "synonyms": ["funny", "amusing"], "antonyms": ["serious", "tragic"], "example": "The clown's act was comical."},
    "commemorate": {"meaning": "to honour the memory of", "synonyms": ["honour", "remember"], "antonyms": ["forget", "ignore"], "example": "The statue commemorates fallen soldiers."},
    "commence": {"meaning": "to begin or start", "synonyms": ["begin", "start"], "antonyms": ["end", "finish"], "example": "The ceremony will commence at noon."},
    "commit": {"meaning": "to carry out or dedicate oneself", "synonyms": ["dedicate", "pledge"], "antonyms": ["abandon", "neglect"], "example": "He committed to finishing the project."},
    "committee": {"meaning": "a group appointed for a task", "synonyms": ["board", "panel"], "antonyms": ["individual", "person"], "example": "The committee met to discuss the budget."},
    "commotion": {"meaning": "a state of noisy confusion", "synonyms": ["disturbance", "uproar"], "antonyms": ["calm", "peace"], "example": "There was a commotion outside the shop."},
    "communicate": {"meaning": "to share information with others", "synonyms": ["convey", "express"], "antonyms": ["withhold", "hide"], "example": "It is important to communicate clearly."},
    "community": {"meaning": "a group of people living together", "synonyms": ["neighbourhood", "society"], "antonyms": ["individual", "isolation"], "example": "The community came together to help."},
    "companion": {"meaning": "a person who accompanies another", "synonyms": ["friend", "partner"], "antonyms": ["stranger", "enemy"], "example": "The dog was her faithful companion."},
    "company": {"meaning": "a business or companionship", "synonyms": ["business", "firm"], "antonyms": ["solitude", "loneliness"], "example": "She enjoys the company of friends."},
}

def read_vocabulary_list(csv_path: Path) -> List[Dict[str, str]]:
    """Read vocabulary list CSV."""
    words = []
    with open(csv_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            words.append({
                'word': row['word'].strip().lower(),
                'level': row['assigned_level'].strip()
            })
    return words

def get_content(word: str) -> Dict:
    """Get content for a word from the database."""
    if word in VOCAB_CONTENT:
        return VOCAB_CONTENT[word]
    return None

def main():
    base_dir = Path(__file__).parent.parent
    data_dir = base_dir / 'data'
    vocab_list_path = data_dir / 'vocabularyList.csv'
    
    print("Reading vocabulary list...")
    words = read_vocabulary_list(vocab_list_path)
    print(f"Total words: {len(words)}")
    
    # Count words with content
    words_with_content = sum(1 for w in words if w['word'] in VOCAB_CONTENT)
    print(f"Words with content defined: {words_with_content}")
    
    # Write vocabulary content
    output_path = data_dir / 'vocabulary_content_new.csv'
    fieldnames = ['word', 'meaning', 'synonym1', 'synonym2', 'antonym1', 'antonym2', 'example_sentence']
    
    with open(output_path, 'w', encoding='utf-8', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        
        for word_data in words:
            word = word_data['word']
            content = get_content(word)
            
            if content:
                writer.writerow({
                    'word': word,
                    'meaning': content['meaning'],
                    'synonym1': content['synonyms'][0] if content['synonyms'] else '',
                    'synonym2': content['synonyms'][1] if len(content['synonyms']) > 1 else '',
                    'antonym1': content['antonyms'][0] if content['antonyms'] else '',
                    'antonym2': content['antonyms'][1] if len(content['antonyms']) > 1 else '',
                    'example_sentence': content['example']
                })
            else:
                # Empty row for words without content
                writer.writerow({
                    'word': word,
                    'meaning': '',
                    'synonym1': '',
                    'synonym2': '',
                    'antonym1': '',
                    'antonym2': '',
                    'example_sentence': ''
                })
    
    print(f"Written to {output_path}")

if __name__ == '__main__':
    main()
